version: '3'
services:
  glassfish:
    image: glassfish:4.1-jdk8
    ports:
      - "8080:8080"
      - "4848:4848"
    volumes:
      - /home/marchlak/Studia/java-zadanka/jpIntelij/out/artifacts/WebServiceGlass/WebServiceGlass.war:/glassfish/domains/domain1/autodeploy/WebServiceGlass.war
